name: Node.js CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev, feature/*, release/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn lint
      - run: yarn build
        env:
          CI: true

  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn jest
        env:
          CI: true

  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          browser: chrome
          headless: true
          start: yarn start
          wait-on: 'http://localhost:3000'
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: __tests__/e2e/videos
